### ISSUE TITLE
[Feature Request] Add support for display parameter

### ISSUE THREAD

**Issue by patorpey** [liorchamla/vsc-google-fonts#10]
Google Font URLs recently began supporting the `display` query parameter to enable setting the CSS `@font-face font-display` descriptor. Google Fonts now appends `&display=swap` to font URLs. It would be useful to also append this, perhaps as an option, to URLs generated by this extension.

**Comment by liorchamla** [comment]
IT IS DONE ! Thanks to @bozzhik !
