### ISSUE TITLE
[Future request] Language selection 

### ISSUE THREAD

**Issue by kanlukasz** [liorchamla/vsc-google-fonts#3]
Hello
A very interesting extension.

Unfortunately, there is no important add option like language selection (`latin-ext` for example)

### My proposition:
1. We choose the font:
![obraz](https://user-images.githubusercontent.com/30685349/69011926-1f0aa580-0970-11ea-8668-2844ade2f15f.png)
2. Then choose an additional language
![obraz](https://user-images.githubusercontent.com/30685349/69012005-fc2cc100-0970-11ea-94d9-9f1d239a6e66.png)

Sorry for no pull request but i'm just php dev

**Comment by liorchamla** [comment]
Ok, i'll take a look when I'll have time to implement this :)

Thx for your feedback

**Comment by kanlukasz** [comment]
Closing due to author's no response for over a year.
